server:
  port: 9092
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.98.132.116:3306/erp_laozhang?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
 #   password: alvin
    password: T_dl123456
  profiles:
    active: dev

application:
  version: 1.0

